class Model {
    entities = new Entities();
};

class Entities {
	item_type = new Item_type(); 
};

class Item_type{
    fields = new Item_type_fields();
};

class Item_type_fields {
    id = { type: 'int', key: true, autogenerated: true };
    name = { type: 'text' };
    is_sellable = { type: 'boolean' };
    amount_type = { type: 'text' };
    buy_cost = { type: 'numeric' };
    sell_price = { type: 'numeric' };
};

module.exports.model = new Model();